import Head from "next/head";
import PageHeader from "./sections/pageheader";
import Pokecards from "./sections/pokecards";
import { Container } from "@mui/material";


export default function Home() {
  return (
    <>
      <Head>
        <title>Pokeapp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/pokeball.ico" />
      </Head>
      <PageHeader />
      <Container>
        <Pokecards />
      </Container>
    </>
  );
}
